# Generated by Django 5.0.4 on 2024-08-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_used', models.CharField(max_length=100)),
                ('bank_account_name', models.CharField(max_length=100)),
                ('date_of_transaction', models.DateField()),
                ('receipt', models.ImageField(upload_to='receipt')),
            ],
        ),
    ]
